variables:
  CODE_DIR: ./projekt

cache:
  key:
    files:
      - $CODE_DIR/package-lock.json
  paths:
    - $CODE_DIR/node_modules/

.node_job:
  tags:
    - pullpolicy
    - myrunner
  image:
    name: node:26
  before_script:
    - cd $CODE_DIR
    - npm ci

test_app:
  extends: .node_job
  stage: test
  allow_failure: false
  script:
    - echo "Running the unit tests..."
    - npm run test:ci

build_app:
  extends: .node_job
  stage: build
  allow_failure: false
  needs: ["test_app"]
  script:
    - echo "Building the Angular app..."
    - npm run build
  artifacts:
    paths:
      - $CODE_DIR/www/*

deploy_app:
  stage: deploy
  tags:
    - myrunner
  image: kroniak/ssh-client
  needs: ["build_app"]
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - scp -o LogLevel=DEBUG -r $CODE_DIR/www/* $USER@$HOST:/srv/uk335/_dr/
    - ssh $USER@$HOST 'cd /srv/uk335 && chmod 755 _dr && mv dr ~dr && mv _dr dr && rm -r ~dr'
