variables:
  CODE_DIR: ./davids-umbrella

build_app:
  stage: build
  tags:
    - pullpolicy
  allow_failure: false
  image: 
    name: node:26
    pull_policy: if-not-present
  script:
    - echo "Building the Angular app..."
    - cd $CODE_DIR
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $CODE_DIR/www/*

deploy_app:
  stage: deploy
  image: kroniak/ssh-client
  needs: ["build_app"]
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - scp -o LogLevel=DEBUG -r $CODE_DIR/www/* $USER@$HOST:/srv/uk335/_dr/
    - ssh $USER@$HOST 'cd /srv/uk335 && chmod 755 _dr && mv dr ~dr && mv _dr dr && rm -r ~dr'
 
